[workspace]
members = ["daemon"]
default-members = [".", "daemon"]

[package]
name = "swww"
version = "0.7.3"
authors = ["Leonardo Gibrowski Faé <leonardo.fae44@gmail.com>"]
edition = "2021"

[profile.release]
debug = 0
lto = true
opt-level = 3
codegen-units = 1
strip = true

[profile.bench]
lto = "thin"
debug = 1
strip = false

[dependencies]
image = "0.24"
fast_image_resize = "2.7"
clap = { version = "4.3", features = ["derive", "wrap_help", "env"] }
rand = "0.8"
utils = { path = "utils" }

[dev-dependencies]
assert_cmd = "2.0"

[build-dependencies]
clap = { version = "4.3", features = ["derive", "env"] }
clap_complete = "4.3"
